### ISSUE TITLE
HifiberryOS, web interface: cannot change page in mobile browser

### ISSUE THREAD

**Issue by KomtGoed** [bang-olufsen/create#82] opened 2020-04-03 08:23 UTC
Hi,

An issue I am having (low prio as I have a workaround): Accessing the HifiberryOS site from a mobile browser (Firefox and Chrome on Android). Both from mobile (rather small screen) as well as tablet.

In all four cases, the browser only display the page that I have visited last through the web browser on my PC (Firefox). For example, when I was on the Source page, that page is displayed and there is no possibility to switch to e.g. settings.

Is this a bug or a feature?
Is linked to the mobile responsiveness feature, when "viewing as desktop site" in Android Firefox, the full page is displayed.

If a feature, I would suggest adding an option in the settings to choose the page that is displayed when accessed through a mobile browser (suggested standard option: sources).

**Comment by tuomashamalainen** [comment] 2020-04-03 08:31
Hey there,

thanks for the kind words. 

The interface will indeed show the screen that was last accessed from the product from any client when the page is loaded – this is by design. However, you should be able to move freely across screens on mobile as well. There should be a black bottom bar that has an upwards chevron on the left (for showing Now Playing), a volume control, and a hamburger button on the right. The hamburger button should show a menu that has all the same items as the top navigation bar in the desktop layout. Are you not seeing this (and if you are, I need to work on making this more obvious)?

**Comment by utereg** [comment] 2020-04-03 20:18
Hey Tuomas,

Thanks for the quick response. The general idea is good, don't get me wrong.

I saw the hamburger and thought it being exactly intended for the purpose you describe.
However, when clicking on it, the page reloaded, no menu shown.

I just tried again and the menu you described opened one time out of the 10+ times I "hamburgered".

What's happening?

**Comment by tuomashamalainen** [comment] 2020-04-03 20:26
That's my fault and a bit embarrassing. This is a "secret feature" that I have neglected to disable for production – it's an invisible reload button that allows me to reload the page when I have it set up such that the browser chrome isn't shown (so that it appears like a native app). This button occupies 20 pt/px from the edge of the screen, so you can hit it accidentally.

I will make sure in the next update that this won't bother you any longer – for now you can try tapping the button on its left side. Sorry about this.

**Comment by utereg** [comment] 2020-04-05 20:57
;) Thanks a lot for the honest answer and no worries
Keep up the good work!

**Comment by tuomashamalainen** [comment] 2020-04-27 13:54
This issue should now be resolved. You can update through the Software Update – observe the following:

1. If your auto-update option is set to "Security only", change it to "Quick".
2. Wait for about 5 minutes.
3. Check for updates again.
4. After updating, you can set the auto-update setting back to your preferred option.

This design flaw has been fixed in the fresh update, and this workaround is not needed in the future.

**Closed by tuomashamalainen** 2020-04-27 13:54 UTC
Labels: bug, next update

**Comment by KomtGoed** [comment] 2020-04-28 21:19
Hi Tuomas,

Thanks for letting me know, works like a charm!

Keep up the good work, sweet piece of software.

All the best and best of health

 Knut
